import { useEffect, useMemo, useState } from "react";
import { Button, Card, Col, Form, Modal, Row, Table } from "react-bootstrap";
import { apiJSON } from "../lib/api";
import { cents, type Budget, type BudgetCategory, type Category, dollars } from "../lib/models";
import { AddButton, TabLayout } from "../components/tab-layout";

const types = ["Yearly", "Monthly", "Weekly", "Daily"];
export default function BudgetPage() {
  const [budgets, setBudgets] = useState<Budget[]>([]), [categories, setCategories] = useState<Category[]>([]), [show, setShow] = useState(false), [editing, setEditing] = useState<Budget | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = async () => { try { const [listed, c] = await Promise.all([apiJSON<Budget[]>("/api/budgets"), apiJSON<Category[]>("/api/categories")]); setBudgets(await Promise.all(listed.map(b => apiJSON<Budget>(`/api/budgets/${b.id}`)))); setCategories(c); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load budgets."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <TabLayout title="Budget" description="Create scenarios, plan spending by category, and compare them with expenses." action={<AddButton label="budget" onClick={() => { setEditing(null); setShow(true); }} />} error={error} loading={loading}>
    {budgets.length === 0 ? <Card body className="text-center py-5 text-body-secondary">Create a budget scenario to begin planning.</Card> : <Row className="g-4">{budgets.map(b => <Col md={6} key={b.id}><Card className="h-100"><Card.Body><div className="d-flex justify-content-between"><Card.Title>{b.name}</Card.Title><span className="text-body-secondary">{types[b.type]}</span></div><div className="display-6">{dollars(b.balance)}</div><small className="text-body-secondary">Available from {dollars(b.net_income)} net income</small><hr />{b.categories.length ? <Table size="sm" borderless className="mb-0"><tbody>{b.categories.map(c => <tr key={c.category_id}><td>{categories.find(x => x.id === c.category_id)?.name ?? "Category"}</td><td className="text-end">{dollars(c.planned_amount)}</td></tr>)}</tbody></Table> : <p className="text-body-secondary mb-0">No planned categories.</p>}</Card.Body></Card></Col>)}</Row>}
    <BudgetModal show={show} categories={categories} onHide={() => setShow(false)} onCreated={b => { setBudgets([b, ...budgets]); setShow(false); }} />
  </TabLayout>;
}
function BudgetModal({ show, categories, onHide, onCreated }: { show: boolean; categories: Category[]; onHide: () => void; onCreated: (b: Budget) => void }) {
  const defaultItems = useMemo(() => categories.filter(c => c.is_default && c.transaction_type === 1).map(c => ({ category_id: c.id, planned_amount: 0 })), [categories]);
  const [name, setName] = useState(""), [income, setIncome] = useState(""), [type, setType] = useState(1), [items, setItems] = useState<BudgetCategory[]>([]), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (show) { setItems(defaultItems); setName(""); setIncome(""); setType(1); setError(""); } }, [show, defaultItems]);
  const balance = cents(income) - items.reduce((sum, item) => sum + item.planned_amount, 0);
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!name.trim() || cents(income) < 0) { setError("Enter a name and a non-negative income."); return; } setSaving(true); try { onCreated(await apiJSON<Budget>("/api/budgets", { method: "POST", body: JSON.stringify({ name, type, net_income: cents(income), balance, categories: items }) })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create budget."); } finally { setSaving(false); } };
  return <Modal show={show} onHide={onHide} size="lg"><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>Create budget</Modal.Title></Modal.Header><Modal.Body>{error && <div className="alert alert-danger">{error}</div>}<Row><Form.Group as={Col} md={7} className="mb-3"><Form.Label>Name</Form.Label><Form.Control required placeholder="e.g. Current monthly plan" value={name} onChange={e => setName(e.target.value)} /></Form.Group><Form.Group as={Col} md={5} className="mb-3"><Form.Label>Period</Form.Label><Form.Select value={type} onChange={e => setType(Number(e.target.value))}>{types.map((t, i) => <option value={i} key={t}>{t}</option>)}</Form.Select></Form.Group></Row><Form.Group className="mb-3"><Form.Label>Net income</Form.Label><Form.Control required type="number" min="0" step="0.01" placeholder="0.00" value={income} onChange={e => setIncome(e.target.value)} /><Form.Text>Enter dollars; stored precisely as cents.</Form.Text></Form.Group><div className="d-flex justify-content-between align-items-center"><h6>Planned categories</h6><strong className={balance < 0 ? "text-danger" : ""}>Remaining: {dollars(balance)}</strong></div><Table responsive size="sm"><tbody>{items.map((item, index) => <tr key={item.category_id}><td>{categories.find(c => c.id === item.category_id)?.name}</td><td><Form.Control aria-label="Planned amount" type="number" min="0" step="0.01" value={(item.planned_amount / 100).toFixed(2)} onChange={e => setItems(items.map((x, i) => i === index ? { ...x, planned_amount: cents(e.target.value) } : x))} /></td><td><Button variant="outline-danger" size="sm" onClick={() => setItems(items.filter((_, i) => i !== index))}>Remove</Button></td></tr>)}</tbody></Table></Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Creating…" : "Create budget"}</Button></Modal.Footer></Form></Modal>;
}
