import { useEffect, useState } from "react";
import { Button, Card, Form, Modal, Table } from "react-bootstrap";
import { apiJSON } from "../lib/api";
import { cents, dollars, type Budget, type BudgetCategory, type Category } from "../lib/models";
import { AddButton, TabLayout } from "../components/tab-layout";

const periods = ["Yearly", "Monthly", "Weekly", "Daily"];
export default function BudgetEditorPage() {
  const [budgets, setBudgets] = useState<Budget[]>([]), [categories, setCategories] = useState<Category[]>([]), [editing, setEditing] = useState<Budget | null>(null), [show, setShow] = useState(false), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = async () => { try { const [listed, cats] = await Promise.all([apiJSON<Budget[]>("/api/budgets"), apiJSON<Category[]>("/api/categories")]); setCategories(cats); setBudgets(await Promise.all(listed.map(b => apiJSON<Budget>(`/api/budgets/${b.id}`)))); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load budgets."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const saved = (budget: Budget) => { setBudgets(existing => editing ? existing.map(b => b.id === budget.id ? budget : b) : [budget, ...existing]); setShow(false); };
  return <TabLayout title="Budget" description="Create scenarios, plan category amounts, and edit them any time." action={<AddButton label="budget" onClick={() => { setEditing(null); setShow(true); }} />} error={error} loading={loading}>
    {budgets.map(b => <Card className="mb-3" key={b.id}><Card.Body><div className="d-flex justify-content-between gap-3"><div><h2 className="h5 mb-1">{b.name}</h2><div className="text-body-secondary">{periods[b.type]} · Net income {dollars(b.net_income)}</div></div><Button variant="outline-primary" onClick={() => { setEditing(b); setShow(true); }}>Edit budget</Button></div><div className={b.balance < 0 ? "fs-4 text-danger mt-3" : "fs-4 mt-3"}>Remaining: {dollars(b.balance)}</div><Table size="sm" className="mt-3 mb-0"><tbody>{b.categories.map(c => <tr key={c.category_id}><td>{categories.find(x => x.id === c.category_id)?.name ?? "Category"}</td><td className="text-end">{dollars(c.planned_amount)}</td></tr>)}</tbody></Table></Card.Body></Card>)}
    {!budgets.length && <Card body className="text-center py-5 text-body-secondary">Create a budget scenario to begin planning.</Card>}
    <BudgetForm show={show} budget={editing} categories={categories} onHide={() => setShow(false)} onSaved={saved} />
  </TabLayout>;
}
function BudgetForm({ show, budget, categories, onHide, onSaved }: { show: boolean; budget: Budget | null; categories: Category[]; onHide: () => void; onSaved: (budget: Budget) => void }) {
  const [name, setName] = useState(""), [income, setIncome] = useState(""), [period, setPeriod] = useState(1), [items, setItems] = useState<BudgetCategory[]>([]), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (!show) return; setName(budget?.name ?? ""); setIncome(budget ? String(budget.net_income / 100) : ""); setPeriod(budget?.type ?? 1); setItems(budget?.categories ?? categories.filter(c => c.is_default && c.transaction_type === 1).map(c => ({ category_id: c.id, planned_amount: 0 }))); setError(""); }, [show, budget, categories]);
  const balance = cents(income) - items.reduce((total, item) => total + item.planned_amount, 0);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) { setError("A budget name is required."); return; } setSaving(true); try { const value = await apiJSON<Budget>(budget ? `/api/budgets/${budget.id}` : "/api/budgets", { method: budget ? "PUT" : "POST", body: JSON.stringify({ name, type: period, net_income: cents(income), balance, categories: items }) }); onSaved(value); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save the budget."); } finally { setSaving(false); } };
  return <Modal show={show} onHide={onHide} size="lg"><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>{budget ? "Edit budget" : "Create budget"}</Modal.Title></Modal.Header><Modal.Body>{error && <div className="alert alert-danger">{error}</div>}<Form.Group className="mb-3"><Form.Label>Name</Form.Label><Form.Control required value={name} onChange={e => setName(e.target.value)} /></Form.Group><Form.Group className="mb-3"><Form.Label>Period</Form.Label><Form.Select value={period} onChange={e => setPeriod(Number(e.target.value))}>{periods.map((name, index) => <option key={name} value={index}>{name}</option>)}</Form.Select></Form.Group><Form.Group className="mb-3"><Form.Label>Net income</Form.Label><Form.Control required type="number" min="0" step="0.01" value={income} onChange={e => setIncome(e.target.value)} /></Form.Group><div className="d-flex justify-content-between"><h3 className="h6">Planned categories</h3><strong className={balance < 0 ? "text-danger" : ""}>Remaining: {dollars(balance)}</strong></div><Table><tbody>{items.map((item, index) => <tr key={item.category_id}><td>{categories.find(c => c.id === item.category_id)?.name}</td><td><Form.Control type="number" min="0" step="0.01" value={(item.planned_amount / 100).toFixed(2)} onChange={e => setItems(items.map((value, i) => i === index ? { ...value, planned_amount: cents(e.target.value) } : value))} /></td><td><Button size="sm" variant="outline-danger" onClick={() => setItems(items.filter((_, i) => i !== index))}>Remove</Button></td></tr>)}</tbody></Table></Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : budget ? "Save changes" : "Create budget"}</Button></Modal.Footer></Form></Modal>;
}
