import { useEffect, useState } from "react";
import { Button, Card, Col, Form, Modal, Row, Table } from "react-bootstrap";
import { apiJSON } from "../lib/api";
import { cents, dollars, occurrencesPerYear, periods, today, type Budget, type BudgetCategory, type Category, type Transaction } from "../lib/models";
import { AddButton, TabLayout } from "../components/tab-layout";

const projectedExpense = (expense: Transaction, targetPeriod: number) => Math.round(
  expense.amount * (expense.recurring ? occurrencesPerYear[expense.recurring_type] / occurrencesPerYear[targetPeriod] : 1),
);

export default function BudgetEditorPage() {
  const [budgets, setBudgets] = useState<Budget[]>([]), [categories, setCategories] = useState<Category[]>([]), [expenses, setExpenses] = useState<Transaction[]>([]);
  const [editingBudget, setEditingBudget] = useState<Budget | null>(null), [addingCategory, setAddingCategory] = useState<Budget | null>(null), [expenseContext, setExpenseContext] = useState<{ budget: Budget; categoryId: number; expense?: Transaction } | null>(null);
  const [deleteBudget, setDeleteBudget] = useState<Budget | null>(null), [deleteExpense, setDeleteExpense] = useState<Transaction | null>(null), [collapsed, setCollapsed] = useState<Record<string, boolean>>({}), [collapsedBudgets, setCollapsedBudgets] = useState<Record<number, boolean>>({}), [projection, setProjection] = useState<Record<number, number>>({}), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = async () => { try { const [listed, cats, txs] = await Promise.all([apiJSON<Budget[]>("/api/budgets"), apiJSON<Category[]>("/api/categories"), apiJSON<Transaction[]>("/api/transactions")]); setBudgets(await Promise.all(listed.map(b => apiJSON<Budget>(`/api/budgets/${b.id}`)))); setCategories(cats); setExpenses(txs.filter(t => t.type === 1)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load budgets."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const removeBudget = async () => { if (!deleteBudget) return; try { await apiJSON(`/api/budgets/${deleteBudget.id}`, { method: "DELETE" }); setBudgets(v => v.filter(b => b.id !== deleteBudget.id)); setExpenses(v => v.map(t => t.budget_id === deleteBudget.id ? { ...t, budget_id: undefined, budget_ratio: 0 } : t)); setDeleteBudget(null); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete budget."); } };
  const removeExpense = async () => { if (!deleteExpense) return; try { await apiJSON(`/api/transactions/${deleteExpense.id}`, { method: "DELETE" }); setDeleteExpense(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete expense."); } };
  return <TabLayout title="Budget" description="Build itemized category budgets and project repeating expenses across time periods." action={<AddButton label="budget" onClick={() => setEditingBudget({ id: 0, name: "", type: 1, net_income: 0, balance: 0, categories: [] })} />} error={error} loading={loading}>
    {budgets.map(b => { const target = projection[b.id] ?? b.type, factor = occurrencesPerYear[b.type] / occurrencesPerYear[target], projectedIncome = Math.round(b.net_income * factor), budgetExpenses = expenses.filter(t => t.budget_id === b.id), projectedExpenses = budgetExpenses.reduce((sum, expense) => sum + projectedExpense(expense, target), 0), projectedBalance = projectedIncome - projectedExpenses, isCollapsed = !!collapsedBudgets[b.id]; return <Card className="mb-3" key={b.id}><Card.Body>
      <div className="d-flex justify-content-between align-items-center gap-2"><button type="button" className="btn btn-link text-decoration-none p-0 text-start" onClick={() => setCollapsedBudgets(v => ({ ...v, [b.id]: !v[b.id] }))} aria-expanded={!isCollapsed}><span aria-hidden="true">{isCollapsed ? "▾" : "▴"}</span> <span className="h5 mb-0">{b.name}</span></button>{!isCollapsed && <div className="d-flex gap-2"><Button variant="outline-primary" onClick={() => setEditingBudget(b)}>Edit Budget</Button><Button variant="outline-danger" onClick={() => setDeleteBudget(b)}>Delete Budget</Button></div>}</div>
      <Row className="mt-3"><Col><div className="text-body-secondary">Net Pay</div><div className="fs-4">{dollars(projectedIncome)}</div></Col><Col><div className="text-body-secondary">Current Balance</div><div className={projectedBalance < 0 ? "fs-4 text-danger" : "fs-4"}>{dollars(projectedBalance)}</div></Col></Row>
      {!isCollapsed && <>
      <div className="d-flex justify-content-between align-items-center gap-2 mt-3"><div className="d-flex align-items-center gap-2"><Form.Label className="mb-0" htmlFor={`projection-${b.id}`}>Project as</Form.Label><Form.Select id={`projection-${b.id}`} className="w-auto" value={target} onChange={e => setProjection(v => ({ ...v, [b.id]: Number(e.target.value) }))}>{periods.map((p, i) => <option key={p} value={i}>{p}</option>)}</Form.Select></div><Button variant="outline-primary" onClick={() => setAddingCategory(b)}>Add Category</Button></div>
      {b.categories.map(c => { const key = `${b.id}-${c.category_id}`, rows = budgetExpenses.filter(t => t.category_id === c.category_id), total = rows.reduce((n, t) => n + projectedExpense(t, target), 0), isCategoryCollapsed = collapsed[key] ?? true; return <div className="border rounded mt-3 p-3" key={key}><div className="d-flex justify-content-between align-items-center"><button type="button" className="btn btn-link text-decoration-none p-0" onClick={() => setCollapsed(v => ({ ...v, [key]: !isCategoryCollapsed }))} aria-expanded={!isCategoryCollapsed}>{isCategoryCollapsed ? "▾" : "▴"} {categories.find(x => x.id === c.category_id)?.name ?? "Category"}</button><strong>{dollars(total)}</strong></div>
        {!isCategoryCollapsed && <><Table responsive size="sm" className="mt-2"><thead><tr><th>Expense</th><th>Recurring</th><th>BudgetRatio</th><th className="text-end">Amount</th><th /></tr></thead><tbody>{rows.map(t => <tr key={t.id}><td>{t.description}</td><td>{t.recurring ? periods[t.recurring_type] : "No"}</td><td>{b.net_income ? `${((t.amount / b.net_income) * 100).toFixed(1)}%` : "0.0%"}</td><td className="text-end">{dollars(projectedExpense(t, target))}</td><td className="text-end"><Button size="sm" variant="outline-primary" className="me-2" onClick={() => setExpenseContext({ budget: b, categoryId: c.category_id, expense: t })}>Edit</Button><Button size="sm" variant="outline-danger" onClick={() => setDeleteExpense(t)}>Delete</Button></td></tr>)}</tbody></Table><Button size="sm" onClick={() => setExpenseContext({ budget: b, categoryId: c.category_id })}>Add expense</Button></>}
      </div>})}</>}
    </Card.Body></Card>})}
    {!budgets.length && <Card body className="text-center py-5 text-body-secondary">Create a budget scenario to begin planning.</Card>}
    <BudgetForm value={editingBudget} categories={categories} onHide={() => setEditingBudget(null)} onSaved={() => { setEditingBudget(null); void load(); }} />
    <AddCategoryForm budget={addingCategory} categories={categories} onHide={() => setAddingCategory(null)} onSaved={() => { setAddingCategory(null); void load(); }} />
    <ExpenseForm context={expenseContext} onHide={() => setExpenseContext(null)} onSaved={() => { setExpenseContext(null); void load(); }} />
    <Confirm show={!!deleteBudget} title="Delete budget?" body={`Delete “${deleteBudget?.name ?? ""}”? Its expenses will be kept but unassigned.`} onCancel={() => setDeleteBudget(null)} onConfirm={removeBudget} />
    <Confirm show={!!deleteExpense} title="Delete expense?" body={`Delete “${deleteExpense?.description ?? ""}”?`} onCancel={() => setDeleteExpense(null)} onConfirm={removeExpense} />
  </TabLayout>;
}

function AddCategoryForm({ budget, categories, onHide, onSaved }: { budget: Budget | null; categories: Category[]; onHide: () => void; onSaved: () => void }) {
  const [mode, setMode] = useState<"existing" | "custom">("existing"), [categoryId, setCategoryId] = useState(""), [customName, setCustomName] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const available = categories.filter(category => category.transaction_type === 1 && !budget?.categories.some(item => item.category_id === category.id));
  useEffect(() => { if (budget) { setMode(available.length ? "existing" : "custom"); setCategoryId(""); setCustomName(""); setError(""); } }, [budget]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!budget) return; let selectedId = Number(categoryId); if (mode === "existing" && !selectedId) { setError("Select a category."); return; } const name = customName.trim(); if (mode === "custom" && !name) { setError("Enter a custom category name."); return; } setSaving(true); try { if (mode === "custom") { const matching = categories.find(category => category.transaction_type === 1 && category.name.toLocaleLowerCase() === name.toLocaleLowerCase()); if (matching && budget.categories.some(item => item.category_id === matching.id)) { setError("That category is already in this budget."); setSaving(false); return; } selectedId = matching?.id ?? (await apiJSON<Category>("/api/categories", { method: "POST", body: JSON.stringify({ name, transaction_type: 1 }) })).id; } await apiJSON(`/api/budgets/${budget.id}`, { method: "PUT", body: JSON.stringify({ ...budget, categories: [...budget.categories, { category_id: selectedId, planned_amount: 0 }] }) }); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add category."); } finally { setSaving(false); } };
  return <Modal show={!!budget} onHide={onHide}><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>Add Category</Modal.Title></Modal.Header><Modal.Body>{error && <div className="alert alert-danger">{error}</div>}<div className="d-flex gap-3 mb-3"><Form.Check type="radio" name="category-mode" label="Existing category" checked={mode === "existing"} disabled={!available.length} onChange={() => setMode("existing")} /><Form.Check type="radio" name="category-mode" label="Custom category" checked={mode === "custom"} onChange={() => setMode("custom")} /></div>{mode === "existing" ? <Form.Group><Form.Label>Category</Form.Label><Form.Select required value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">Choose a category</option>{available.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</Form.Select></Form.Group> : <Form.Group><Form.Label>Custom category name</Form.Label><Form.Control required maxLength={100} value={customName} onChange={e => setCustomName(e.target.value)} placeholder="e.g. Pet care" /></Form.Group>}</Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Adding…" : "Add Category"}</Button></Modal.Footer></Form></Modal>;
}

function BudgetForm({ value, categories, onHide, onSaved }: { value: Budget | null; categories: Category[]; onHide: () => void; onSaved: () => void }) {
  const [name, setName] = useState(""), [income, setIncome] = useState(""), [period, setPeriod] = useState(1), [items, setItems] = useState<BudgetCategory[]>([]), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (!value) return; setName(value.name); setIncome(value.id ? String(value.net_income / 100) : ""); setPeriod(value.type); setItems(value.id ? value.categories : categories.filter(c => c.is_default && c.transaction_type === 1).map(c => ({ category_id: c.id, planned_amount: 0 }))); setError(""); }, [value, categories]);
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!value) return; setSaving(true); try { const nextIncome = cents(income), allocated = items.reduce((n, x) => n + x.planned_amount, 0), balance = value.id ? value.balance + nextIncome - value.net_income : nextIncome - allocated; await apiJSON(value.id ? `/api/budgets/${value.id}` : "/api/budgets", { method: value.id ? "PUT" : "POST", body: JSON.stringify({ name, type: period, net_income: nextIncome, balance, categories: items }) }); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save budget."); } finally { setSaving(false); } };
  return <Modal show={!!value} onHide={onHide}><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>{value?.id ? "Edit budget" : "Create budget"}</Modal.Title></Modal.Header><Modal.Body>{error && <div className="alert alert-danger">{error}</div>}<Form.Group className="mb-3"><Form.Label>Name</Form.Label><Form.Control required value={name} onChange={e => setName(e.target.value)} /></Form.Group><Row><Form.Group as={Col}><Form.Label>Period</Form.Label><Form.Select value={period} onChange={e => setPeriod(Number(e.target.value))}>{periods.map((p, i) => <option value={i} key={p}>{p}</option>)}</Form.Select></Form.Group><Form.Group as={Col}><Form.Label>Net income</Form.Label><Form.Control required type="number" min="0" step="0.01" value={income} onChange={e => setIncome(e.target.value)} /></Form.Group></Row>{value?.id ? <div className="mt-3"><h3 className="h6">Categories</h3>{items.length ? <Table size="sm" className="mb-0"><tbody>{items.map(item => <tr key={item.category_id}><td>{categories.find(category => category.id === item.category_id)?.name ?? "Category"}</td><td className="text-end"><Button type="button" size="sm" variant="outline-danger" onClick={() => setItems(current => current.filter(category => category.category_id !== item.category_id))}>Remove</Button></td></tr>)}</tbody></Table> : <p className="text-body-secondary mb-0">No categories in this budget.</p>}<Form.Text>Removing a category keeps its expenses in the budget but makes them uncategorized.</Form.Text></div> : <Form.Text>Category totals are calculated from the expenses you add after saving.</Form.Text>}</Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save budget"}</Button></Modal.Footer></Form></Modal>;
}

function ExpenseForm({ context, onHide, onSaved }: { context: { budget: Budget; categoryId: number; expense?: Transaction } | null; onHide: () => void; onSaved: () => void }) {
  const [description, setDescription] = useState(""), [amount, setAmount] = useState(""), [date, setDate] = useState(today()), [recurring, setRecurring] = useState(false), [recurringType, setRecurringType] = useState(1), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (!context) return; const t = context.expense; setDescription(t?.description ?? ""); setAmount(t ? String(t.amount / 100) : ""); setDate(t?.date.slice(0, 10) ?? today()); setRecurring(t?.recurring ?? false); setRecurringType(t?.recurring_type ?? 1); setError(""); }, [context]);
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!context) return; setSaving(true); try { const t = context.expense; await apiJSON(t ? `/api/transactions/${t.id}` : "/api/transactions", { method: t ? "PUT" : "POST", body: JSON.stringify({ description, amount: cents(amount), type: 1, date, budget_id: context.budget.id, category_id: context.categoryId, recurring, recurring_type: recurringType }) }); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save expense."); } finally { setSaving(false); } };
  return <Modal show={!!context} onHide={onHide}><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>{context?.expense ? "Edit expense" : "Add expense"}</Modal.Title></Modal.Header><Modal.Body>{error && <div className="alert alert-danger">{error}</div>}<Form.Group className="mb-3"><Form.Label>Description</Form.Label><Form.Control required value={description} onChange={e => setDescription(e.target.value)} /></Form.Group><Row><Form.Group as={Col}><Form.Label>Amount</Form.Label><Form.Control required type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></Form.Group><Form.Group as={Col}><Form.Label>Date</Form.Label><Form.Control required type="date" value={date} onChange={e => setDate(e.target.value)} /></Form.Group></Row><div className="d-flex align-items-end gap-3 mt-3"><Form.Check label="Recurring?" checked={recurring} onChange={e => setRecurring(e.target.checked)} />{recurring && <Form.Group><Form.Label>Frequency</Form.Label><Form.Select value={recurringType} onChange={e => setRecurringType(Number(e.target.value))}>{periods.map((p, i) => <option value={i} key={p}>{p}</option>)}</Form.Select></Form.Group>}</div></Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save expense"}</Button></Modal.Footer></Form></Modal>;
}

function Confirm({ show, title, body, onCancel, onConfirm }: { show: boolean; title: string; body: string; onCancel: () => void; onConfirm: () => void }) { return <Modal show={show} onHide={onCancel}><Modal.Header closeButton><Modal.Title>{title}</Modal.Title></Modal.Header><Modal.Body>{body}</Modal.Body><Modal.Footer><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button variant="danger" onClick={onConfirm}>Delete</Button></Modal.Footer></Modal>; }
