import { useEffect, useState } from "react";
import { Button, Card, Form, Modal, Table } from "react-bootstrap";
import { apiJSON } from "../lib/api";
import { cents, dollars, today, type Budget, type Category, type Property, type Transaction } from "../lib/models";
import { AddButton, TabLayout } from "../components/tab-layout";

export default function ExpensesEditorPage() {
  const [items, setItems] = useState<Transaction[]>([]), [budgets, setBudgets] = useState<Budget[]>([]), [categories, setCategories] = useState<Category[]>([]), [properties, setProperties] = useState<Property[]>([]), [show, setShow] = useState(false), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([apiJSON<Transaction[]>("/api/transactions"), apiJSON<Budget[]>("/api/budgets"), apiJSON<Category[]>("/api/categories"), apiJSON<Property[]>("/api/properties")]).then(([transactions, budgetList, categoryList, propertyList]) => { setItems(transactions); setBudgets(budgetList); setCategories(categoryList); setProperties(propertyList); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load expenses.")).finally(() => setLoading(false)); }, []);
  return <TabLayout title="Expenses" description="Add manual expenses and link them to your budget categories." action={<AddButton label="expense" onClick={() => setShow(true)} />} error={error} loading={loading}>
    {items.length ? <Table responsive><thead><tr><th>Date</th><th>Description</th><th>Budget</th><th>Category</th><th className="text-end">Amount</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.date.slice(0, 10)}</td><td>{item.description}</td><td>{budgets.find(b => b.id === item.budget_id)?.name ?? "—"}</td><td>{categories.find(c => c.id === item.category_id)?.name ?? "—"}</td><td className="text-end">{dollars(item.amount)}</td></tr>)}</tbody></Table> : <Card body className="text-center py-5 text-body-secondary">No expenses yet.</Card>}
    <ExpenseForm show={show} budgets={budgets} categories={categories} properties={properties} onHide={() => setShow(false)} onAdded={item => { setItems(current => [item, ...current]); setShow(false); }} />
  </TabLayout>;
}
function ExpenseForm({ show, budgets, categories, properties, onHide, onAdded }: { show: boolean; budgets: Budget[]; categories: Category[]; properties: Property[]; onHide: () => void; onAdded: (item: Transaction) => void }) {
  const [description, setDescription] = useState(""), [amount, setAmount] = useState(""), [date, setDate] = useState(today()), [budget, setBudget] = useState(""), [category, setCategory] = useState(""), [property, setProperty] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (show) { setDescription(""); setAmount(""); setDate(today()); setBudget(""); setCategory(""); setProperty(""); setError(""); } }, [show]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); const value = cents(amount); if (value <= 0) { setError("Enter an amount greater than zero."); return; } setSaving(true); try { onAdded(await apiJSON<Transaction>("/api/transactions", { method: "POST", body: JSON.stringify({ description, amount: value, type: 1, date, budget_id: budget ? Number(budget) : undefined, category_id: category ? Number(category) : undefined, property_id: property ? Number(property) : undefined }) })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add expense."); } finally { setSaving(false); } };
  return <Modal show={show} onHide={onHide}><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>Add expense</Modal.Title></Modal.Header><Modal.Body>{error && <div className="alert alert-danger">{error}</div>}<Form.Group className="mb-3"><Form.Label>Description</Form.Label><Form.Control required value={description} onChange={e => setDescription(e.target.value)} /></Form.Group><Form.Group className="mb-3"><Form.Label>Amount</Form.Label><Form.Control required type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></Form.Group><Form.Group className="mb-3"><Form.Label>Date</Form.Label><Form.Control required type="date" value={date} onChange={e => setDate(e.target.value)} /></Form.Group><Form.Group className="mb-3"><Form.Label>Budget <span className="text-body-secondary">(optional)</span></Form.Label><Form.Select value={budget} onChange={e => setBudget(e.target.value)}><option value="">No budget</option>{budgets.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Form.Select></Form.Group><Form.Group className="mb-3"><Form.Label>Category <span className="text-body-secondary">(optional)</span></Form.Label><Form.Select value={category} onChange={e => setCategory(e.target.value)}><option value="">Uncategorized</option>{categories.filter(item => item.transaction_type === 1).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Form.Select><Form.Text>When this category exists in the selected budget, its allocation and the remaining balance are updated together.</Form.Text></Form.Group><Form.Group><Form.Label>Property <span className="text-body-secondary">(optional)</span></Form.Label><Form.Select value={property} onChange={e => setProperty(e.target.value)}><option value="">No property</option>{properties.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Form.Select></Form.Group></Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Add expense"}</Button></Modal.Footer></Form></Modal>;
}
