import { useEffect, useMemo, useState } from "react";
import { Button, Card, Col, Form, Modal, Row, Table } from "react-bootstrap";
import { apiJSON } from "../lib/api";
import { cents, dollars, periods, today, type Budget, type Category, type Property, type Transaction } from "../lib/models";
import { AddButton, TabLayout } from "../components/tab-layout";

type SortKey = "date" | "description" | "budget" | "category" | "recurring" | "budgetRatio" | "amount";

export default function ExpensesEditorPage() {
  const [items, setItems] = useState<Transaction[]>([]), [budgets, setBudgets] = useState<Budget[]>([]), [categories, setCategories] = useState<Category[]>([]), [properties, setProperties] = useState<Property[]>([]), [editing, setEditing] = useState<Transaction | null | undefined>(), [deleting, setDeleting] = useState<Transaction | null>(null), [sort, setSort] = useState<{ key: SortKey; direction: "asc" | "desc" }>({ key: "date", direction: "desc" }), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = async () => { try { const [t, b, c, p] = await Promise.all([apiJSON<Transaction[]>("/api/transactions"), apiJSON<Budget[]>("/api/budgets"), apiJSON<Category[]>("/api/categories"), apiJSON<Property[]>("/api/properties")]); setItems(t.filter(x => x.type === 1)); setBudgets(b); setCategories(c); setProperties(p); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load expenses."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const sortedItems = useMemo(() => {
    const budgetName = (item: Transaction) => budgets.find(b => b.id === item.budget_id)?.name ?? "";
    const categoryName = (item: Transaction) => categories.find(c => c.id === item.category_id)?.name ?? "";
    const value = (item: Transaction): string | number => ({ date: item.date, description: item.description, budget: budgetName(item), category: categoryName(item), recurring: item.recurring ? periods[item.recurring_type] : "", budgetRatio: item.budget_ratio, amount: item.amount }[sort.key]);
    return [...items].sort((a, b) => { const left = value(a), right = value(b); const result = typeof left === "number" && typeof right === "number" ? left - right : String(left).localeCompare(String(right), undefined, { sensitivity: "base" }); return sort.direction === "asc" ? result : -result; });
  }, [items, budgets, categories, sort]);
  const changeSort = (key: SortKey) => setSort(current => ({ key, direction: current.key === key && current.direction === "asc" ? "desc" : "asc" }));
  const remove = async () => { if (!deleting) return; try { await apiJSON(`/api/transactions/${deleting.id}`, { method: "DELETE" }); setDeleting(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete expense."); } };
  return <TabLayout title="Expenses" description="Add manual expenses and link them to your budget categories." action={<AddButton label="expense" onClick={() => setEditing(null)} />} error={error} loading={loading}>
    {items.length ? <Table responsive><thead><tr><SortableHeader label="Date" sortKey="date" sort={sort} onSort={changeSort} /><SortableHeader label="Description" sortKey="description" sort={sort} onSort={changeSort} /><SortableHeader label="Budget" sortKey="budget" sort={sort} onSort={changeSort} /><SortableHeader label="Category" sortKey="category" sort={sort} onSort={changeSort} /><SortableHeader label="Recurring" sortKey="recurring" sort={sort} onSort={changeSort} /><SortableHeader label="BudgetRatio" sortKey="budgetRatio" sort={sort} onSort={changeSort} /><SortableHeader label="Amount" sortKey="amount" sort={sort} onSort={changeSort} alignRight /><th aria-label="Actions" /></tr></thead><tbody>{sortedItems.map(item => <tr key={item.id}><td>{item.date.slice(0, 10)}</td><td>{item.description}</td><td>{budgets.find(b => b.id === item.budget_id)?.name ?? "—"}</td><td>{categories.find(c => c.id === item.category_id)?.name ?? "—"}</td><td>{item.recurring ? periods[item.recurring_type] : "No"}</td><td>{item.budget_id ? `${item.budget_ratio.toFixed(1)}%` : "—"}</td><td className="text-end">{dollars(item.amount)}</td><td className="text-nowrap"><Button size="sm" variant="outline-primary" className="me-2" onClick={() => setEditing(item)}>Edit</Button><Button size="sm" variant="outline-danger" onClick={() => setDeleting(item)}>Delete</Button></td></tr>)}</tbody></Table> : <Card body className="text-center py-5 text-body-secondary">No expenses yet.</Card>}
    <ExpenseForm open={editing !== undefined} expense={editing ?? null} budgets={budgets} categories={categories} properties={properties} onHide={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); void load(); }} />
    <Modal show={!!deleting} onHide={() => setDeleting(null)}><Modal.Header closeButton><Modal.Title>Delete expense?</Modal.Title></Modal.Header><Modal.Body>Delete “{deleting?.description}”?</Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setDeleting(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete</Button></Modal.Footer></Modal>
  </TabLayout>;
}

function SortableHeader({ label, sortKey, sort, onSort, alignRight = false }: { label: string; sortKey: SortKey; sort: { key: SortKey; direction: "asc" | "desc" }; onSort: (key: SortKey) => void; alignRight?: boolean }) {
  const active = sort.key === sortKey;
  return <th className={alignRight ? "text-end" : undefined} aria-sort={active ? (sort.direction === "asc" ? "ascending" : "descending") : "none"}><button type="button" className="btn btn-link p-0 text-decoration-none text-body fw-semibold" onClick={() => onSort(sortKey)}>{label} <span aria-hidden="true">{active ? (sort.direction === "asc" ? "▲" : "▼") : "↕"}</span></button></th>;
}

function ExpenseForm({ open, expense, budgets, categories, properties, onHide, onSaved }: { open: boolean; expense: Transaction | null; budgets: Budget[]; categories: Category[]; properties: Property[]; onHide: () => void; onSaved: () => void }) {
  const [description, setDescription] = useState(""), [amount, setAmount] = useState(""), [date, setDate] = useState(today()), [budget, setBudget] = useState(""), [category, setCategory] = useState(""), [property, setProperty] = useState(""), [recurring, setRecurring] = useState(false), [recurringType, setRecurringType] = useState(1), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { if (!open) return; setDescription(expense?.description ?? ""); setAmount(expense ? String(expense.amount / 100) : ""); setDate(expense?.date.slice(0, 10) ?? today()); setBudget(expense?.budget_id ? String(expense.budget_id) : ""); setCategory(expense?.category_id ? String(expense.category_id) : ""); setProperty(expense?.property_id ? String(expense.property_id) : ""); setRecurring(expense?.recurring ?? false); setRecurringType(expense?.recurring_type ?? 1); setError(""); }, [open, expense]);
  const save = async (e: React.FormEvent) => { e.preventDefault(); const value = cents(amount); if (value <= 0) { setError("Enter an amount greater than zero."); return; } setSaving(true); try { await apiJSON(expense ? `/api/transactions/${expense.id}` : "/api/transactions", { method: expense ? "PUT" : "POST", body: JSON.stringify({ description, amount: value, type: 1, date, budget_id: budget ? Number(budget) : undefined, category_id: category ? Number(category) : undefined, property_id: property ? Number(property) : undefined, recurring, recurring_type: recurringType }) }); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save expense."); } finally { setSaving(false); } };
  return <Modal show={open} onHide={onHide}><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>{expense ? "Edit expense" : "Add expense"}</Modal.Title></Modal.Header><Modal.Body>{error && <div className="alert alert-danger">{error}</div>}<Form.Group className="mb-3"><Form.Label>Description</Form.Label><Form.Control required value={description} onChange={e => setDescription(e.target.value)} /></Form.Group><Row><Form.Group as={Col}><Form.Label>Amount</Form.Label><Form.Control required type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></Form.Group><Form.Group as={Col}><Form.Label>Date</Form.Label><Form.Control required type="date" value={date} onChange={e => setDate(e.target.value)} /></Form.Group></Row><Form.Group className="mt-3"><Form.Label>Budget</Form.Label><Form.Select value={budget} onChange={e => setBudget(e.target.value)}><option value="">No budget</option>{budgets.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</Form.Select></Form.Group><Form.Group className="mt-3"><Form.Label>Category</Form.Label><Form.Select value={category} onChange={e => setCategory(e.target.value)}><option value="">Uncategorized</option>{categories.filter(c => c.transaction_type === 1).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Form.Select></Form.Group><Form.Group className="mt-3"><Form.Label>Property</Form.Label><Form.Select value={property} onChange={e => setProperty(e.target.value)}><option value="">No property</option>{properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</Form.Select></Form.Group><div className="d-flex align-items-end gap-3 mt-3"><Form.Check label="Recurring?" checked={recurring} onChange={e => setRecurring(e.target.checked)} />{recurring && <Form.Group><Form.Label>Frequency</Form.Label><Form.Select value={recurringType} onChange={e => setRecurringType(Number(e.target.value))}>{periods.map((p, i) => <option key={p} value={i}>{p}</option>)}</Form.Select></Form.Group>}</div></Modal.Body><Modal.Footer><Button variant="secondary" onClick={onHide}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save expense"}</Button></Modal.Footer></Form></Modal>;
}
