import { useEffect, useMemo, useState } from "react";
import { Card, Col, Container, Form, Row, Spinner } from "react-bootstrap";
import { Link } from "react-router";
import type { Route } from "./+types/home";
import { AuthenticatedPage } from "../components/authenticated-page";
import { AppNavbar } from "../components/navbar";
import { apiJSON } from "../lib/api";
import { dollars, type Account, type Budget, type Loan, type Property, type Transaction } from "../lib/models";

export function meta({}: Route.MetaArgs) { return [{ title: "Financial Overview | Insight" }, { name: "description", content: "A complete view of your finances." }]; }

type Period = "all" | "ytd" | "past" | "month" | "week" | "day";
type Metric = "income" | "expenses" | "investments" | "properties" | "loans" | "accounts" | "netWorth";
const metricInfo: Record<Metric, { label: string; color: string }> = {
  income: { label: "Income", color: "#198754" }, expenses: { label: "Expenses", color: "#dc3545" }, investments: { label: "Investments", color: "#6f42c1" }, properties: { label: "Properties", color: "#0dcaf0" }, loans: { label: "Loans", color: "#fd7e14" }, accounts: { label: "Accounts", color: "#0d6efd" }, netWorth: { label: "Net Worth", color: "#212529" },
};
const allMetrics = Object.keys(metricInfo) as Metric[];

export default function Home() {
  const [transactions, setTransactions] = useState<Transaction[]>([]), [budgets, setBudgets] = useState<Budget[]>([]), [properties, setProperties] = useState<Property[]>([]), [loans, setLoans] = useState<Loan[]>([]), [accounts, setAccounts] = useState<Account[]>([]), [selectedMetrics, setSelectedMetrics] = useState<Metric[]>(allMetrics), [includeProperties, setIncludeProperties] = useState(true), [chartPeriod, setChartPeriod] = useState<Period>("ytd"), [chartMonth, setChartMonth] = useState(() => localMonth(new Date())), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([apiJSON<Transaction[]>("/api/transactions"), apiJSON<Budget[]>("/api/budgets"), apiJSON<Property[]>("/api/properties"), apiJSON<Loan[]>("/api/loans"), apiJSON<Account[]>("/api/accounts")]).then(([t, b, p, l, a]) => { setTransactions(t); setBudgets(b); setProperties(p); setLoans(l); setAccounts(a); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load your financial overview.")).finally(() => setLoading(false)); }, []);
  const totals = useMemo(() => {
    const income = transactions.filter(t => t.type === 0).reduce((sum, t) => sum + t.amount, 0), expenses = transactions.filter(t => t.type === 1).reduce((sum, t) => sum + t.amount, 0);
    const accountAssets = accounts.filter(a => a.account_type !== "credit_card").reduce((sum, a) => sum + a.balance, 0), cardDebt = accounts.filter(a => a.account_type === "credit_card").reduce((sum, a) => sum + a.balance, 0), propertyValue = properties.reduce((sum, p) => sum + (p.current_value ?? 0), 0), loanDebt = loans.reduce((sum, l) => sum + l.current_balance, 0), investments = 0;
    return { income, expenses, accounts: accountAssets - cardDebt, propertyValue, loanDebt, investments, netWorth: income - expenses + accountAssets + investments - cardDebt - loanDebt + (includeProperties ? propertyValue : 0) };
  }, [transactions, properties, loans, accounts, includeProperties]);
  const chart = useMemo(() => buildChartData(transactions, totals, includeProperties, chartPeriod, chartMonth), [transactions, totals, includeProperties, chartPeriod, chartMonth]);
  return <AuthenticatedPage><AppNavbar /><Container className="py-4"><div className="mb-4"><h1 className="mb-1">Your financial overview</h1><p className="text-body-secondary mb-0">Income, spending, assets, and liabilities in one place.</p></div>{error && <div className="alert alert-danger">{error}</div>}{loading ? <div className="text-center py-5"><Spinner /><span className="visually-hidden">Loading</span></div> : <>
    <Card className="mb-4 shadow-sm"><Card.Body><div className="d-flex flex-wrap justify-content-between gap-3 mb-3"><div><h2 className="h5 mb-1">Financial trends</h2><div className="text-body-secondary">Activity over time and current balance snapshots</div></div><div className="d-flex flex-wrap align-items-center gap-3"><Form.Select aria-label="Chart time period" className="w-auto" value={chartPeriod} onChange={e => setChartPeriod(e.target.value as Period)}><option value="all">All time</option><option value="ytd">Year to date</option><option value="past">Past month</option><option value="month">This month</option><option value="week">This week</option><option value="day">Today</option></Form.Select>{chartPeriod === "past" && <Form.Control type="month" aria-label="Chart past month" className="w-auto" value={chartMonth} max={localMonth(new Date())} onChange={e => setChartMonth(e.target.value)} />}<Form.Check type="switch" id="property-net-worth" label="Include property in Net Worth" checked={includeProperties} onChange={e => setIncludeProperties(e.target.checked)} /></div></div><div className="d-flex flex-wrap gap-3 mb-2">{allMetrics.map(metric => <Form.Check key={metric} id={`metric-${metric}`} label={metricInfo[metric].label} checked={selectedMetrics.includes(metric)} onChange={e => setSelectedMetrics(current => e.target.checked ? [...current, metric] : current.filter(item => item !== metric))} />)}</div><div className="d-flex flex-wrap gap-3 mb-3" aria-label="Chart key">{selectedMetrics.map(metric => <span key={metric} className="d-inline-flex align-items-center gap-1"><span aria-hidden="true" style={{ width: 14, height: 4, background: metricInfo[metric].color, display: "inline-block" }} />{metricInfo[metric].label}</span>)}</div><FinancialChart points={chart} selected={selectedMetrics} /></Card.Body></Card>
    <Row className="g-4 mb-4"><Col lg={6}><CashFlowWidget title="Income" type={0} transactions={transactions} /></Col><Col lg={6}><CashFlowWidget title="Expenses" type={1} transactions={transactions} /></Col></Row>
    <Row className="g-4"><Preview title="Budgets" to="/budget" total={`${budgets.length} active`} items={budgets.slice(0, 3).map(b => ({ name: b.name, value: dollars(b.balance) }))} empty="No budgets yet" /><Preview title="Accounts" to="/accounts" total={dollars(totals.accounts)} items={accounts.slice(0, 3).map(a => ({ name: a.name, value: dollars(a.balance) }))} empty="No accounts yet" /><Preview title="Properties" to="/properties" total={dollars(totals.propertyValue)} items={properties.slice(0, 3).map(p => ({ name: p.name, value: p.current_value === undefined ? "Value not set" : dollars(p.current_value) }))} empty="No properties yet" /><Preview title="Investments" to="/investments" total={dollars(totals.investments)} items={[]} empty="No tracked investments yet" /><Preview title="Loans" to="/loans" total={dollars(totals.loanDebt)} items={loans.slice(0, 3).map(l => ({ name: l.name, value: dollars(l.current_balance) }))} empty="No loans yet" /><Col md={6} xl={4}><Card className="h-100 border-primary"><Card.Body><div className="text-body-secondary">Estimated Net Worth</div><div className={totals.netWorth < 0 ? "display-6 text-danger" : "display-6"}>{dollars(totals.netWorth)}</div><small className="text-body-secondary">Cash flow + assets − cards − loans{includeProperties ? " + property" : ""}</small></Card.Body></Card></Col></Row>
  </>}</Container></AuthenticatedPage>;
}

function CashFlowWidget({ title, type, transactions }: { title: string; type: number; transactions: Transaction[] }) {
  const [period, setPeriod] = useState<Period>("month"), [pastMonth, setPastMonth] = useState(() => { const d = new Date(); d.setMonth(d.getMonth() - 1); return localMonth(d); });
  const now = new Date(), ytd = sumPeriod(transactions, type, "ytd", pastMonth, now), month = sumPeriod(transactions, type, "month", pastMonth, now), selected = sumPeriod(transactions, type, period, pastMonth, now);
  return <Card className="h-100"><Card.Body><div className="d-flex justify-content-between align-items-start gap-3"><div><Card.Title>{title}</Card.Title><div className="display-6">{dollars(selected)}</div><small className="text-body-secondary">Selected period</small></div><Form.Select aria-label={`${title} period`} className="w-auto" value={period} onChange={e => setPeriod(e.target.value as Period)}><option value="all">All time</option><option value="ytd">Year to date</option><option value="past">Past month</option><option value="month">This month</option><option value="week">This week</option><option value="day">Today</option></Form.Select></div>{period === "past" && <Form.Control className="mt-3" type="month" aria-label={`${title} past month`} value={pastMonth} max={localMonth(now)} onChange={e => setPastMonth(e.target.value)} />}<Row className="mt-3"><Col><div className="text-body-secondary">YTD</div><strong>{dollars(ytd)}</strong></Col><Col><div className="text-body-secondary">This month</div><strong>{dollars(month)}</strong></Col></Row></Card.Body></Card>;
}

function Preview({ title, to, total, items, empty }: { title: string; to: string; total: string; items: { name: string; value: string }[]; empty: string }) { return <Col md={6} xl={4}><Card className="h-100"><Card.Body><div className="d-flex justify-content-between"><Card.Title>{title}</Card.Title><Link to={to}>View all</Link></div><div className="h4">{total}</div>{items.length ? <div className="mt-3">{items.map(item => <div className="d-flex justify-content-between border-top py-2" key={item.name}><span>{item.name}</span><span>{item.value}</span></div>)}</div> : <p className="text-body-secondary mb-0 mt-3">{empty}</p>}</Card.Body></Card></Col>; }

type ChartPoint = { label: string; major: boolean } & Record<Metric, number>;
function FinancialChart({ points, selected }: { points: ChartPoint[]; selected: Metric[] }) {
  const width = 960, height = 320, left = 88, right = 20, top = 18, bottom = 52, values = points.flatMap(point => selected.map(metric => point[metric])), min = Math.min(0, ...values), max = Math.max(1, ...values), range = max - min || 1, x = (index: number) => left + index * ((width - left - right) / Math.max(1, points.length - 1)), y = (value: number) => height - bottom - ((value - min) / range) * (height - top - bottom), yTicks = Array.from({ length: 6 }, (_, index) => min + range * (index / 5));
  return <div className="overflow-auto"><svg role="img" aria-label="Financial metrics over time, dollar values on the vertical axis" viewBox={`0 0 ${width} ${height}`} className="w-100" style={{ minWidth: 700 }}>{yTicks.map(value => <g key={value}><line x1={left} y1={y(value)} x2={width - right} y2={y(value)} stroke="#e3e6e8" /><text x={left - 8} y={y(value) + 4} fontSize="11" textAnchor="end" fill="#6c757d">{compactDollars(value)}</text></g>)}<text x="16" y={height / 2} transform={`rotate(-90 16 ${height / 2})`} fontSize="12" textAnchor="middle" fill="#6c757d">Dollars</text>{points.map((point, index) => <g key={index}><line x1={x(index)} y1={height - bottom} x2={x(index)} y2={height - bottom + (point.major ? 8 : 4)} stroke="#6c757d" />{point.major && <text x={x(index)} y={height - 20} fontSize="11" textAnchor="middle" fill="#6c757d">{point.label}</text>}</g>)}<line x1={left} y1={y(0)} x2={width - right} y2={y(0)} stroke="#6c757d" />{selected.map(metric => <polyline key={metric} fill="none" stroke={metricInfo[metric].color} strokeWidth={metric === "netWorth" ? 3 : 2} points={points.map((point, index) => `${x(index)},${y(point[metric])}`).join(" ")} />)}</svg>{!selected.length && <div className="text-center text-body-secondary">Select at least one metric.</div>}</div>;
}

type TimeBucket = { start: Date; end: Date; label: string; major: boolean };
function buildChartData(transactions: Transaction[], totals: { accounts: number; propertyValue: number; loanDebt: number; investments: number }, includeProperties: boolean, period: Period, selectedMonth: string): ChartPoint[] {
  const buckets = chartBuckets(period, selectedMonth, transactions), dated = transactions.map(transaction => ({ transaction, date: transactionDate(transaction) })); let cumulativeCashFlow = 0;
  return buckets.map(bucket => { const matching = dated.filter(item => item.date >= bucket.start && item.date < bucket.end), income = matching.filter(item => item.transaction.type === 0).reduce((sum, item) => sum + item.transaction.amount, 0), expenses = matching.filter(item => item.transaction.type === 1).reduce((sum, item) => sum + item.transaction.amount, 0); cumulativeCashFlow += income - expenses; return { label: bucket.label, major: bucket.major, income, expenses, investments: totals.investments, properties: totals.propertyValue, loans: totals.loanDebt, accounts: totals.accounts, netWorth: cumulativeCashFlow + totals.accounts + totals.investments - totals.loanDebt + (includeProperties ? totals.propertyValue : 0) }; });
}
function chartBuckets(period: Period, selectedMonth: string, transactions: Transaction[]): TimeBucket[] {
  const now = new Date(); now.setMinutes(0, 0, 0);
  if (period === "day") { const start = new Date(now); start.setHours(0); return Array.from({ length: 24 }, (_, hour) => bucket(addHours(start, hour), addHours(start, hour + 1), `${hour === 0 ? 12 : hour > 12 ? hour - 12 : hour}${hour < 12 ? "am" : "pm"}`, true)); }
  if (period === "week") { const start = new Date(now); start.setHours(0); start.setDate(start.getDate() - ((start.getDay() + 6) % 7)); return Array.from({ length: 7 }, (_, day) => { const date = addDays(start, day); return bucket(date, addDays(date, 1), date.toLocaleDateString(undefined, { weekday: "short" }), true); }); }
  if (period === "month" || period === "past") { const [year, month] = (period === "past" ? selectedMonth : localMonth(now)).split("-").map(Number), start = new Date(year, month - 1, 1), days = new Date(year, month, 0).getDate(); return Array.from({ length: days }, (_, index) => { const date = addDays(start, index), week = Math.floor(index / 7) + 1; return bucket(date, addDays(date, 1), `Week ${week}`, index % 7 === 0); }); }
  if (period === "ytd") { const start = new Date(now.getFullYear(), 0, 1), result: TimeBucket[] = []; for (let date = start, lastMonth = -1; date <= now; date = addDays(date, 7)) { const end = addDays(date, 7), major = date.getMonth() !== lastMonth; result.push(bucket(date, end, date.toLocaleDateString(undefined, { month: "short" }), major)); lastMonth = date.getMonth(); } return result; }
  const dates = transactions.map(transactionDate), earliest = dates.length ? new Date(Math.min(...dates.map(Number))) : addMonths(new Date(now.getFullYear(), now.getMonth(), 1), -11), start = new Date(earliest.getFullYear(), earliest.getMonth(), 1), result: TimeBucket[] = []; for (let date = start; date <= now; date = addMonths(date, 1)) { const major = date.getMonth() === 0 || result.length === 0; result.push(bucket(date, addMonths(date, 1), String(date.getFullYear()), major)); } return result;
}
function bucket(start: Date, end: Date, label: string, major: boolean): TimeBucket { return { start, end, label, major }; }
function addHours(date: Date, count: number) { const result = new Date(date); result.setHours(result.getHours() + count); return result; }
function addDays(date: Date, count: number) { const result = new Date(date); result.setDate(result.getDate() + count); return result; }
function addMonths(date: Date, count: number) { const result = new Date(date); result.setMonth(result.getMonth() + count); return result; }
function compactDollars(cents: number) { const dollarsValue = cents / 100, absolute = Math.abs(dollarsValue); if (absolute >= 1_000_000) return `${dollarsValue < 0 ? "-" : ""}$${(absolute / 1_000_000).toFixed(1)}M`; if (absolute >= 1_000) return `${dollarsValue < 0 ? "-" : ""}$${(absolute / 1_000).toFixed(1)}K`; return `${dollarsValue < 0 ? "-" : ""}$${absolute.toFixed(0)}`; }
function sumPeriod(items: Transaction[], type: number, period: Period, pastMonth: string, now: Date) { return items.filter(item => item.type === type && inPeriod(transactionDate(item), period, pastMonth, now)).reduce((sum, item) => sum + item.amount, 0); }
function inPeriod(date: Date, period: Period, pastMonth: string, now: Date) { if (period === "all") return true; if (period === "ytd") return date.getFullYear() === now.getFullYear() && date <= now; if (period === "past") return localMonth(date) === pastMonth; if (period === "month") return sameMonth(date, now); if (period === "day") return date.toDateString() === now.toDateString(); const start = new Date(now); start.setHours(0, 0, 0, 0); start.setDate(now.getDate() - ((now.getDay() + 6) % 7)); return date >= start && date <= now; }
function sameMonth(a: Date, b: Date) { return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth(); }
function localMonth(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; }
function transactionDate(transaction: Transaction) { return new Date(`${transaction.date.slice(0, 10)}T00:00:00`); }
